#yml  文件不能使用制表空格tab    
#设置值只能使用 :(空格)值
server:
 port: 80
 
 
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/c85-s2-ply-damai?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    
   
     #邮件发送 yml 配置规则，如果某个阶段有重复配置的
  mail:
      #发送邮件服务器
    host: smtp.qq.com 
    #发送邮件的邮箱地址  用户名
    username: 632360579@qq.com
    #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的 qq授权码
    password:  kbkhfogxgvvebdff 
    default-encoding: UTF-8
 
   
logging:
  level:
    com:
      yc:
       c83.springboot.ll:
       dao: debug
       web: warn

#自定义
mail:
 fromMail:
   addr: 632360579@qq.com
