server:
 port: 8002
 

#定义当前服务名称
spring:
   application:
    name: order
#配置eureka服务器的地址
eureka:
   client:
     serviceUrl:
       defaultZone: http://es1:8000/eureka,http://es2:7999/eureka
       
#yml支持同一个文件内部的配置块  方式： 使用   ---    分割每一个配置块    每个配置块都要有名字    没有名字就是默认配置块
---
server:
 port: 8007
#spring认识的id配置(配置 配重块名）
spring:
   profiles: order8007

 

 
---
server:
 port: 8008
 
spring:
  profiles: order8008