server:
 port: 80
 
 
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/llblog?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    
   
logging:
  level:
    com:
      yc:
       c83.s3.llblog: debug
      